/**:
  ros__parameters:
    wheel_radius: 0.287 # The radius of the wheel, primarily used for dead reckoning.
    wheel_width: 0.141 # The lateral width of a wheel tire, primarily used for dead reckoning.
    wheel_base: 1.718 # between front wheel center and rear wheel center
    wheel_tread: 1.140 # between left wheel center and right wheel center
    front_overhang: 0.370 # between front wheel center and vehicle front
    rear_overhang: 0.750 # between rear wheel center and vehicle rear
    left_overhang: 0.070 # between left wheel center and vehicle left
    right_overhang: 0.070 # between right wheel center and vehicle right
    vehicle_height: 1.615
    max_steer_angle: 29.461 # [rad]
